---
title: "day01"
author: "Gillian McGinnis"
date: "11/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(ggrepel)
library(janitor)
library(ggthemes)
library(wesanderson)
```

```{r dataframes}
# Loading data; source: https://github.com/Reed-Statistics/data-viz-competition-2020
rm(list = ls())

diversity_school <- 
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/diversity_school.csv") %>%
  dplyr::select(-X1)

historical_tuition <- 
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/historical_tuition.csv") %>%
  dplyr::select(-X1)

salary_potential <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/salary_potential.csv") %>%
  dplyr::select(-X1)

tuition_cost <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/tuition_cost.csv") %>% 
  dplyr::select(-X1)

tuition_income <-
  read_csv("https://raw.githubusercontent.com/Reed-Statistics/data-viz-competition-2020/main/data/tuition_income.csv") %>%
  dplyr::select(-X1)
```

```{r plots}
filtered_diversity <- diversity_school %>%
  filter(name == "University of Arizona") %>%
  filter(category != "Women",
         category != "Total Minority")

ggplot(filtered_diversity, aes(x = category, y = enrollment))+
  geom_point()



filtered_cost <- tuition_cost %>%
  filter(state_code == "AZ",
         type == "For Profit")

ggplot(filtered_cost, aes(x = name, y = in_state_total))+
  geom_point()


filtered_potential <- salary_potential %>%
  filter(state_name == "Oregon") %>%
  select(!rank)

ggplot(filtered_potential, aes(x = make_world_better_percent, y = stem_percent, label = name))+
  geom_point()+
  geom_text_repel(size=2)
  #geom_text(position = "dodge", nudge = )
  #geom_label(aes(label = name), position = "dodge", check_overlap=TRUE, size=1)

ggplot(filtered_potential, aes(x = make_world_better_percent, y = mid_career_pay, label = name))+
  geom_point(aes(y = early_career_pay))+
  geom_point(aes(y = mid_career_pay))+
  geom_text_repel(size = 2)


filtered_longer <- filtered_potential %>%
  pivot_longer(cols = ends_with("pay"), names_to = "time", values_to = "pay") %>%
  group_by(name)

ggplot(filtered_longer, aes(x = make_world_better_percent, y = pay, label = name, color = time, group = name))+
  geom_line(color = "green")+
  geom_point()


ggplot(salary_potential, aes(x = early_career_pay, y = mid_career_pay, color = state_name))+
  geom_point(alpha=.3)


combinedDivSal <- full_join(diversity_school, salary_potential)

combinedDivSalFiltered <- combinedDivSal %>%
  clean_names("small_camel") %>%
  drop_na() %>%
  filter(category %in% c("Total Minority", "White")) %>%
  group_by(name) %>%
  filter(state == "Arizona")

ggplot(combinedDivSalFiltered, aes(x = makeWorldBetterPercent, y = enrollment, color = category))+
  geom_point()

combinedGender <- combinedDivSal %>%
  clean_names("small_camel") %>%
  drop_na() %>%
  filter(category == "Women") %>%
  mutate(men = totalEnrollment - enrollment) %>%
  select(!c(totalEnrollment, category)) %>%
  rename(women = enrollment) %>%
  pivot_longer(cols = c(women, men), names_to = "gender", values_to = "pop")

combinedGenderFiltered <- combinedGender %>%
  filter(state == "California") %>%
  mutate(salChange = (((midCareerPay - earlyCareerPay)/earlyCareerPay)*100))

ggplot(combinedGenderFiltered, aes(x = salChange, y = pop, color = gender, group = name))+
  geom_point()+
  geom_line(color = "green")+
  scale_color_manual(values = c("women" = "deeppink", "men" = "blue"))
  
```

```{r tuition}
histTuition <- historical_tuition %>%
  clean_names("small_camel") %>%
  filter(tuitionType == c("All Constant", "All Current")) %>%
  unite("both", c(tuitionType, type), remove = FALSE)
  # mutate(years = case_when(
  #   tuitionType == str_detect("2 Year") ~ "2 Year",
  #   tutionType == str_detect("4 Year") ~ "4 Year"
  # ))

money <- salary_potential %>%
  summary(mean = mean(mid_career_pay))

ggplot(histTuition, aes(x = year, y = tuitionCost, color = type, shape = tuitionType, group = type))+
  geom_point()+
  geom_line(aes(group = both))+
  #geom_line()+
  theme_few()+
  theme(axis.text.x = element_text(angle = 30,
                                   vjust = 0.7))
```


```{r heatmap}
ggplot(tuition_cost, aes(x = type, y = state_code, fill = out_of_state_total))+
  geom_tile()

cut_diversity <- diversity_school %>%
  filter(category != "White",
         category != "Women",
         category != "Total Minority") %>%
  group_by(state) %>%
  filter(state %in% c("Arizona", "Alabama", "California", "Oregon", "New York", "New Mexico"))

ggplot(cut_diversity, aes(x = category, y = state, fill = enrollment))+
  #geom_bin2d()
  geom_tile()
  #geom_raster()
#sad

```

```{r maps}
ggplot(tuition_cost, aes(fill = out_of_state_total, map_id = state))+
  geom_map(map = map_data("state"))

states_map <- as.data.frame(apply(map_data("state"),2,str_to_title)) %>%
  rename(state = region)

tuition_map <- left_join(states_map, tuition_cost, by = "state") %>%
  group_by(long, lat)

ggplot(tuition_map, aes(x=long, y=lat))+
  geom_polygon(aes(fill = out_of_state_total))
#whelp it's getting there
```

```{r hexmap}
#library(geojsonsf)
#https://www.r-graph-gallery.com/328-hexbin-map-of-the-usa.html
```

```{r women stem}
full_div_sal <- full_join(diversity_school, salary_potential)

filtered_div_sal <- full_div_sal %>%
  drop_na() %>%
  filter(category == "Women") %>%
  mutate(men = total_enrollment - enrollment) %>%
  rename(women = enrollment) %>%
  pivot_longer(cols = c(women, men), names_to = "gender", values_to = "enrollment") %>%
  select(!c(total_enrollment, category, rank, state_name)) %>%
  group_by(name)

ggplot(filtered_div_sal, aes(x = enrollment, y = stem_percent, color = gender, fill = gender))+
  #geom_point(alpha=0.5)+
  geom_smooth()+
  #geom_quantile()+ #interesting but honestly I'm not sure how to interpret
  scale_color_manual(values = c(men = "blue", women = "hotpink"))+
  scale_fill_manual(values = c(men = "blue", women = "hotpink"))+
  theme_few()

mini_ds <- filtered_div_sal  %>%
  filter(state == "California")

ggplot(mini_ds, aes(x = enrollment, y = stem_percent, color = gender, fill = gender))+
  geom_point(alpha=0.5)+
  #geom_smooth()+
  #geom_quantile()+ #interesting but honestly I'm not sure how to interpret
  scale_color_manual(values = c(men = "blue", women = "hotpink"))+
  scale_fill_manual(values = c(men = "blue", women = "hotpink"))+
  theme_few()


percent_div_sal <- full_div_sal %>%
  drop_na() %>%
  filter(category == "Women") %>%
  mutate(women = (enrollment/total_enrollment)*100,
         #men = 100-women,
         men = ((total_enrollment-enrollment)/total_enrollment)*100) %>%
  select(!c(total_enrollment, category, rank, state_name, enrollment)) %>%
  pivot_longer(cols = c(women, men), names_to = "gender", values_to = "enrollment") %>%
  group_by(name)

#ok this looks pretty cool but not super helpful
ggplot(percent_div_sal, aes(x = enrollment, y = stem_percent, color = gender, fill = gender))+
  geom_point(alpha=0.5)+
  #geom_smooth()+
  #geom_quantile()+ #interesting but honestly I'm not sure how to interpret
  scale_color_manual(values = c(men = "blue", women = "hotpink"))+
  scale_fill_manual(values = c(men = "blue", women = "hotpink"))+
  theme_few()

ggplot(subset(percent_div_sal, gender == "women"), aes(x = enrollment, y = stem_percent, color = gender, fill = gender))+
  geom_point(alpha=0.5)+
  #geom_smooth()+
  #geom_quantile()+ #interesting but honestly I'm not sure how to interpret
  scale_color_manual(values = c(men = "blue", women = "hotpink"))+
  scale_fill_manual(values = c(men = "blue", women = "hotpink"))+
  theme_few()
  
```

```{r diversity stem}
full_div_sal <- full_join(diversity_school, salary_potential)

percent_min_sal <- full_div_sal %>%
  drop_na() %>%
  filter(category == "Total Minority") %>%
  mutate(minority = (enrollment/total_enrollment)*100,
         #men = 100-women,
         non = ((total_enrollment-enrollment)/total_enrollment)*100) %>%
  select(!c(total_enrollment, category, rank, state_name, enrollment)) %>%
  pivot_longer(cols = c(minority, non), names_to = "minority", values_to = "enrollment") %>%
  group_by(name)

ggplot(percent_min_sal, aes(x = enrollment, y = stem_percent, color = minority, fill = minority))+
  geom_point(alpha=0.5)+
  theme_few()

ggplot(subset(percent_min_sal, minority == "minority"), aes(x = enrollment, y = stem_percent))+
  geom_point(alpha=0.5, color = "blue")+
  #geom_smooth()+
  #geom_quantile()+ #interesting but honestly I'm not sure how to interpret
  theme_few()
```

```{r animated}
full_div_sal <- full_join(diversity_school, salary_potential)

div_sal <- full_div_sal %>%
  drop_na() %>%
  mutate(percent = (enrollment/total_enrollment)*100) %>%
  select(!c(total_enrollment, rank, state_name, early_career_pay, mid_career_pay)) %>%
  group_by(name)

## first animation!!
ggplot(div_sal, aes(x = percent, y = stem_percent, color = category, group = category))+
  geom_point()+
  transition_states(category,
                    transition_length = 2,
                    state_length = 1)

ggplot(div_sal, aes(x = percent, y = stem_percent))+
  geom_point(alpha=0.3)+
  facet_wrap(~category)

div_sal_wm <- full_div_sal %>%
  drop_na() %>%
  select(!c(rank, state_name, early_career_pay, mid_career_pay)) %>%
  pivot_wider(names_from = category, values_from = enrollment) %>%
  mutate(Men = total_enrollment-Women) %>%
  pivot_longer(cols = c(6:17), names_to = "category", values_to = "enrollment") %>%
  mutate(percent = (enrollment/total_enrollment)*100)

div_sal_gender <- div_sal_wm %>%
  filter(category %in% c("Women", "Men"))

div_sal_now <- div_sal_wm %>%
  filter(category != c("White", "Men", "Women"))

div_sal_white <- div_sal_wm %>%
  filter(category == "White") %>%
  select(!c(category))

div_sal_men <- div_sal_wm %>%
  filter(category == "Men") %>%
  select(!c(category))

ggplot(div_sal_men, aes(x = percent, y = stem_percent))+
  geom_point()+
  geom_rug()

ggplot(div_sal_now, aes(x = percent, y = stem_percent))+
  #geom_point(data=div_sal_men, color = "blue", alpha = 0.1)+
  geom_point(data=div_sal_white, color = "red", alpha = 0.1, shape = 10)+
  geom_point(alpha=0.3, color = "blue")+
  facet_wrap(~category)+
  theme_few()

ggplot(div_sal_now, aes(x = percent, y = stem_percent))+
  #geom_rug(data=div_sal_men, color = "blue", alpha = 0.1)+
  geom_rug(data=div_sal_white, color = "red", alpha = 0.1)+
  geom_point(alpha=0.3, color = "blue")+
  facet_wrap(~category)+
  theme_few()

```

```{r percentages}
big_data <- diversity_school %>%
  full_join(salary_potential) %>%
  full_join(tuition_cost) %>%
  full_join(tuition_income) %>%
  group_by(category) %>%
  mutate(row = row_number()) %>%
  pivot_wider(names_from = category, values_from = enrollment) %>%
  select(-row) %>%
  mutate(Men = total_enrollment-Women)

big_data_per <- diversity_school %>%
  full_join(salary_potential) %>%
  full_join(tuition_cost) %>%
  #full_join(tuition_income) %>%
  group_by(category) %>%
  mutate(enrollment_per = (enrollment/total_enrollment)*100) %>%
  select(!c(enrollment, state_name)) %>%
  mutate(row = row_number()) %>%
  pivot_wider(names_from = category, values_from = enrollment_per) %>%
  select(-c(row,'NA')) %>%
  mutate(Men = (100-Women))

big_data_long <- big_data_per %>%
  pivot_longer(cols=17:28, names_to = "category", values_to = "enrollment_per")

ggplot(big_data_long, aes(x = state, y = enrollment_per, color = category))+
  geom_point(alpha=0.3)+
  coord_flip()+
  facet_wrap(~category)

big_data_state <- big_data_long %>%
  drop_na(enrollment_per, state) %>%
  group_by(state, category) %>%
  summarize(mean = mean(enrollment_per))
  #filter(state %in% c("Washington", "Oregon", "California"))

ggplot(big_data_state, aes(x = state, y = mean))+
  geom_point(alpha=0.3)+
  coord_flip()+
  facet_wrap(~category)+
  theme_few()

big_data_west <- big_data_long %>%
  filter(state %in% c("Washington", "Oregon", "California")) %>%
  drop_na(type)

ggplot(big_data_west, aes(x = state, y = enrollment_per, color = type))+
  geom_boxplot(alpha=0.5)+
  coord_flip()+
  facet_wrap(~category)+
  theme_few()

ggplot(subset(big_data_west, category == c("Women", "Men")), aes(x = state, y = enrollment_per, color = type))+
  geom_boxplot(alpha=0.5)+
  coord_flip()+
  facet_wrap(~category)+
  theme_few()

ggplot(subset(big_data_west, category == c("Women", "Men")), aes(x = type, y = enrollment_per, color = category))+
  geom_boxplot()+
  coord_flip()+
  facet_wrap(~state)+
  theme_few()

ggplot(subset(big_data_west, category == c("Total Minority")), aes(x = type, y = enrollment_per, color = category))+
  geom_violin()+
  geom_jitter(alpha=0.3)+
  #coord_flip()+
  facet_wrap(~state)+
  theme_few()

# state source: https://worldpopulationreview.com/states/state-abbreviations
states <- read_csv("data/states.csv") %>%
  clean_names()

big_data_coord <- big_data_state %>%
  #filter(category %in% c("Men", "Women"))
  filter(category == "Total Minority") %>%
  full_join(states) %>%
  drop_na()

## Here too!
ggplot(big_data_coord, aes(x = abbrev, y = mean, fill = mean))+
  geom_col()+
  coord_polar()+
  aes(x=reorder(abbrev, mean))+
  theme_light()+
  theme(axis.text.x = element_text(angle=-20))+
  scale_fill_gradientn(colors = wes_palette(name = "Zissou1", type="continuous"))+
  labs(x = "", y = "Mean Percentage", fill = "Mean Percentage")

ggplot(big_data_coord, aes(x = abbrev, y = mean, fill = mean))+
  geom_col()+
  ylim(0, 100)+
  coord_polar()+
  aes(x=reorder(abbrev, mean))+
  theme_light()+
  theme(axis.text.x = element_text(angle=-20))+
  scale_fill_gradientn(colors = wes_palette(name = "Zissou1", type="continuous"))+
  labs(x = "", y = "Mean Percentage", fill = "Mean Percentage")

big_data_coord_region <- big_data_coord %>%
  full_join(census_regions) %>%
  drop_na(mean) %>%
  group_by(division) %>%
  summarize(mean_div = mean(mean))

# here too I guess
ggplot(big_data_coord_region, aes(x = division, y = mean_div, fill = mean_div))+
  geom_col()+
  #ylim(0, 100)+
  coord_polar()+
  aes(x=reorder(division, mean_div))+
  theme_light()+
  theme(axis.text.x = element_text(angle=-20))+
  scale_fill_gradientn(colors = wes_palette(name = "Zissou1", type="continuous"))+
  labs(x = "", y = "Mean Percentage", fill = "Mean Percentage")


big_data_gender <- big_data_state %>%
  filter(category %in% c("Men", "Women")) %>%
  pivot_wider(names_from = category, values_from = mean) %>%
  arrange(Women) %>%
  pivot_longer(cols = c("Men", "Women"), names_to = "category", values_to = "mean") %>%
  ungroup() %>%
  mutate(row = row_number()) %>%
  full_join(states) %>%
  drop_na()

## Down here!
ggplot(big_data_gender, aes(x = reorder(abbrev,row), y = mean, fill = category))+
  geom_col()+
  coord_polar()+
  scale_fill_manual(values = c(Men = "palegreen1", Women = "mediumpurple1"))+
  theme_few()+
  theme(axis.text.x = element_text(angle=-20))

ggplot(big_data_gender, aes(x = reorder(abbrev, row), y = mean, fill = category))+
  geom_col()+
  geom_text(data=subset(big_data_gender, category == "Women"), aes(label=code),vjust=0,color="black",size=2,angle=-20)+
  coord_polar()+
  theme_light()+
  theme(axis.text.x = element_text(angle=-20))





library(ggridges)

big_data_ridge <- big_data_long %>%
  full_join(states) %>%
  drop_na()

ggplot(subset(big_data_ridge, category == c("Total Minority")), aes(x = enrollment_per, y = state, fill = type))+
  geom_density_ridges(alpha=0.5)+
  theme_ridges()+
  theme_few()

# library(RCurl)
# census_url <- getURL("https://github.com/cphalpert/census-regions/blob/master/us%20census%20bureau%20regions%20and%20divisions.csv")
census_regions <- read_csv("https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv") %>%
  clean_names()

big_data_subset <- big_data_ridge %>%
  full_join(census_regions)

ggplot(subset(big_data_subset, category == c("Total Minority")), aes(x = enrollment_per, y = region, fill = type))+
  geom_density_ridges(alpha=0.5)+
  scale_fill_manual(values = wes_palette(name = "Darjeeling1"))+
  #theme_ridges()+
  theme_few()

## Down here!
ggplot(subset(big_data_subset, category == c("Total Minority")), aes(x = enrollment_per, y = region, color = type))+
  geom_violin()+
  geom_point(position=position_jitterdodge(), alpha=0.3)+
  #geom_jitter(alpha=0.5)+
  scale_color_manual(values = wes_palette(name = "GrandBudapest2", 2, type="continuous"))+
  #theme_ridges()+
  theme_few()

ggplot(subset(big_data_subset, category == c("Total Minority")), aes(x = enrollment_per, y = region, fill = division))+
  geom_density_ridges(alpha=0.5)+
  facet_wrap(~type)+
  scale_fill_manual(values = wes_palette(9, name = "Zissou1", type = "continuous"))+
  #theme_ridges()+
  theme_few()

big_data_sw <- big_data_long %>%
  filter(state %in% c("Arizona", "Texas", "New Mexico", "Utah", "Colorado")) %>%
  drop_na(type)

ggplot(subset(big_data_sw, category == c("Total Minority")), aes(x = enrollment_per, y = state, fill = category))+
  geom_density_ridges()+
  theme_ridges()+
  theme_few()

big_data_sw_filtered <- big_data_sw %>%
  filter(category != "Total Minority",
         category != "White",
         category != "Men",
         category != "Women")

ggplot(big_data_sw_filtered, aes(x = enrollment_per, y = state, fill = category))+
  geom_density_ridges(alpha=0.5)+
  theme_ridges()+
  theme_few()

ggplot(subset(big_data_sw, category == c("Total Minority")), aes(x = enrollment_per, y = state, fill = type))+
  geom_density_ridges(alpha=0.5)+
  theme_ridges()+
  theme_few()

# #install.packages("geojsonio")
# install.packages("devtools")
# devtools::install_github("ropensci/geojsonio")
# library("geojsonio")
# 
# install.packages("ropensci/geojsonio", repo='https://github.com/ropensci/geojsonio')
```



